In [21]:
from sklearn.cluster import MeanShift
import numpy as np
import pandas as pd 
from sklearn.preprocessing import StandardScaler
import operator

In [ ]:
data = pd.read_csv("training_features_triplets.csv")
data = data.drop(['userID'], axis=1) 
z_scaler = StandardScaler()
z_scaler.fit(data)
data = z_scaler.transform(data)

In [30]:
def cluster_stats(labels):
    print("No of different labels: ", len(set(labels)))
    d = {}
    for i in labels:
        if i in d:
            d[i] += 1
        else:
            d[i] = 1
    print("Max number of keys in a cluster: ", max(list(d.values())))
    print("Min number of keys in a cluster: ", min(list(d.values())))

# Bandwidth = 2

In [16]:
clustering_1 = MeanShift(bandwidth=2).fit(data)
print(clustering_1.labels_)

[   0    0   58 ...    0    0 1667]


In [31]:
clsuter_labels_list_1 = clustering_1.labels_
print(clsuter_labels_list_1)
#print("No of different labels: ", len(set(clsuter_labels_list_1)))
cluster_stats(clsuter_labels_list_1)

[   0    0   58 ...    0    0 1667]
No of different labels:  1668
Max number of keys in a cluster:  4554
Min number of keys in a cluster:  1


# Bandwidth is calculated 

In [27]:
clustering_2 = MeanShift().fit(data)
print(clustering_2.labels_)

[ 0  0  2 ...  0  0 99]


In [35]:
clsuter_labels_list_2 = clustering_2.labels_
print(clsuter_labels_list_2)
#print("No of different labels: ", len(set(clsuter_labels_list_1)))
cluster_stats(clsuter_labels_list_2)

[ 0  0  2 ...  0  0 99]
No of different labels:  657
Max number of keys in a cluster:  6670
Min number of keys in a cluster:  1


# Without clustering all points

In [36]:
clustering_3 = MeanShift(cluster_all=False).fit(data)
print(clustering_3.labels_)

[ 0  0  2 ...  0  0 -1]


In [37]:
clsuter_labels_list_3 = clustering_3.labels_
print(clsuter_labels_list_3)
#print("No of different labels: ", len(set(clsuter_labels_list_1)))
cluster_stats(clsuter_labels_list_3)

[ 0  0  2 ...  0  0 -1]
No of different labels:  658
Max number of keys in a cluster:  6291
Min number of keys in a cluster:  1


## no change from clustering 2